import { Secretaria } from '../types';

export const INITIAL_SECRETARIAS: Secretaria[] = [
  {
    id: 'sec-1',
    pasta: 'Administração',
    isFemaleSecretary: false,
    responsavel: 'Gecimar Jorge de Aragão',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-2',
    pasta: 'Agricultura e Pecuária',
    isFemaleSecretary: false,
    responsavel: 'Wagner de Barros Soares',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-3',
    pasta: 'Assistência Social e Cidadania',
    isFemaleSecretary: true,
    responsavel: 'Dryene Tavares Areas Silva',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-4',
    pasta: 'Assuntos Religiosos',
    isFemaleSecretary: false,
    responsavel: 'Pastor Sérgio Luis de Sousa',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-5',
    pasta: 'Bem-Estar Animal',
    isFemaleSecretary: false,
    responsavel: 'Robson Teixeira da Silva - Robgol',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-6',
    pasta: 'Ciência e Tecnologia',
    isFemaleSecretary: true,
    responsavel: 'Sabrina dos Santos Alves',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-7',
    pasta: 'Comunicação Social',
    isFemaleSecretary: false,
    responsavel: 'Keffin Gracher',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-8',
    pasta: 'Cultura e das Utopias',
    isFemaleSecretary: false,
    responsavel: 'Sady Bianchin',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-9',
    pasta: 'Defesa do Consumidor',
    isFemaleSecretary: false,
    responsavel: 'Rick Aquino',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-10',
    pasta: 'Direitos Humanos – SDH',
    isFemaleSecretary: false,
    responsavel: 'João Carlos de Lima - Birigu',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-11',
    pasta: 'Economia Solidária e Empreendedorismo Social',
    isFemaleSecretary: false,
    responsavel: 'Matheus Silva do Amparo - Matheus Gaúcho',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-12',
    pasta: 'Educação',
    isFemaleSecretary: false,
    responsavel: 'Professor Rodrigo Moura',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-13',
    pasta: 'Energias Renováveis e Iluminação Pública',
    isFemaleSecretary: true,
    responsavel: 'Veronica da Silva Costa Faria',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-14',
    pasta: 'Especial de Promoção das Comunidades e do Minha Casa, Minha Vida',
    isFemaleSecretary: true,
    responsavel: 'Brunna Letícia de Oliveira Tavares - Brunna Índia',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-15',
    pasta: 'Esportes',
    isFemaleSecretary: false,
    responsavel: 'Filipe Dias Bittencourt',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-16',
    pasta: 'Executiva de Gestão de Governo',
    isFemaleSecretary: false,
    responsavel: 'Felippe Gomes Lima (interino)',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-17',
    pasta: 'Gestão Tributária e Fiscal',
    isFemaleSecretary: true,
    responsavel: 'Lawrice dos Santos Souza',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-18',
    pasta: 'Governança em Licitações e Contratos',
    isFemaleSecretary: false,
    responsavel: 'Felippe Gomes Lima',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-19',
    pasta: 'Habitação',
    isFemaleSecretary: false,
    responsavel: 'Marcus Toselli - Marcus Bambam',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-20',
    pasta: 'Justiça e Cidadania',
    isFemaleSecretary: false,
    responsavel: 'Eduardo Carlos de Souza',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-21',
    pasta: 'Juventude e Participação Popular',
    isFemaleSecretary: true,
    responsavel: 'Andressa Verônica da Silva Santos',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-22',
    pasta: 'Lutas e Esportes de Combate de Base e Alto Rendimento',
    isFemaleSecretary: false,
    responsavel: 'Thiago da Silva Reis',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-23',
    pasta: 'Meio Ambiente e Sustentabilidade',
    isFemaleSecretary: false,
    responsavel: 'Helter Viana Ferreira de Almeida',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-24',
    pasta: 'Pesca',
    isFemaleSecretary: false,
    responsavel: 'Alexandre Rodrigues de Oliveira - Xandi de Bambuí',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-25',
    pasta: 'Pessoa com Deficiência e Inclusão',
    isFemaleSecretary: true,
    responsavel: 'Tatiana Vieira da Costa Castro dos Santos - Tatiana Castor',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-26',
    pasta: 'Planejamento, Contabilidade e Finanças – SEPCOF',
    isFemaleSecretary: false,
    responsavel: 'Joab Santana de Carvalho',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-27',
    pasta: 'Políticas de Desenvolvimento Regional e Articulação com o CONLESTE (SEDRACON)',
    isFemaleSecretary: true,
    responsavel: 'Priscilla Canedo Loureiro',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-28',
    pasta: 'Políticas e Defesa dos Direitos das Mulheres',
    isFemaleSecretary: true,
    responsavel: 'Ingrid Caldas Pereira de Almeida Bastos',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-29',
    pasta: 'Políticas para Terceira Idade – SPTI',
    isFemaleSecretary: false,
    responsavel: 'Amarildo Ribeiro da Silva',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-30',
    pasta: 'Promoção de Eventos (SEV)',
    isFemaleSecretary: false,
    responsavel: 'Rony Peterson Dias da Silva',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-31',
    pasta: 'Proteção e Defesa Civil',
    isFemaleSecretary: false,
    responsavel: 'Carlos Danilo dos Santos',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-32',
    pasta: 'Qualidade de Vida, Bem-Estar Social e Entretenimento',
    isFemaleSecretary: false,
    responsavel: 'Reinaldo da Silva Cunha',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-33',
    pasta: 'Recursos Hídricos e Minerais',
    isFemaleSecretary: false,
    responsavel: 'Julio Cesar Silva Santos - Julio Carolino',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-34',
    pasta: 'Relações Internacionais',
    isFemaleSecretary: false,
    responsavel: 'Jorge Luiz Cordeiro da Costa - Castor',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-35',
    pasta: 'Representação e Articulação Institucional',
    isFemaleSecretary: true,
    responsavel: 'Ivana Cristina Melo de Moura',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-36',
    pasta: 'Saúde',
    isFemaleSecretary: false,
    responsavel: 'Marcelo Costa Velho Mendes de Azevedo',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-37',
    pasta: 'Segurança Cidadã (SESEG)',
    isFemaleSecretary: false,
    responsavel: 'Julio Cesar Veras Vieira',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-38',
    pasta: 'Trabalho e Emprego',
    isFemaleSecretary: false,
    responsavel: 'Thiago dos Santos Monteiro',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-39',
    pasta: 'Transição Climática e Resiliência Ambiental',
    isFemaleSecretary: false,
    responsavel: 'Richard Alter Seal',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-40',
    pasta: 'Transportes e Postura – SEMTRANS',
    isFemaleSecretary: false,
    responsavel: 'Andre Luis Azeredo da Silva - André Casquinha',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-41',
    pasta: 'Trânsito – SECTRAN',
    isFemaleSecretary: false,
    responsavel: 'Márcio da Silva Carvalho - Marcinho da Construção',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-42',
    pasta: 'Turismo, Comércio, Indústria e Mercado Interno – STCIM',
    isFemaleSecretary: true,
    responsavel: 'Júlia Britto',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
  {
    id: 'sec-43',
    pasta: 'Urbanismo e Planejamento Territorial',
    isFemaleSecretary: true,
    responsavel: 'Sheila Nazareth Rodrigues',
    quemSao: '',
    oqueFazem: '',
    enderecos: [],
    telefones: [],
    ramais: [],
    emails: []
  },
];